(cl:defpackage roborex-srv
  (:use )
  (:export
   "FORWARDKINEMATICS"
   "<FORWARDKINEMATICS-REQUEST>"
   "FORWARDKINEMATICS-REQUEST"
   "<FORWARDKINEMATICS-RESPONSE>"
   "FORWARDKINEMATICS-RESPONSE"
   "INVERSEKINEMATICS"
   "<INVERSEKINEMATICS-REQUEST>"
   "INVERSEKINEMATICS-REQUEST"
   "<INVERSEKINEMATICS-RESPONSE>"
   "INVERSEKINEMATICS-RESPONSE"
   "TRAJECTORYPLANNER"
   "<TRAJECTORYPLANNER-REQUEST>"
   "TRAJECTORYPLANNER-REQUEST"
   "<TRAJECTORYPLANNER-RESPONSE>"
   "TRAJECTORYPLANNER-RESPONSE"
  ))

