(cl:defpackage roborex-srv
  (:use )
  (:export
   "FORWARDKINEMATICS"
   "<FORWARDKINEMATICS-REQUEST>"
   "FORWARDKINEMATICS-REQUEST"
   "<FORWARDKINEMATICS-RESPONSE>"
   "FORWARDKINEMATICS-RESPONSE"
   "INVERSEKINEMATICS"
   "<INVERSEKINEMATICS-REQUEST>"
   "INVERSEKINEMATICS-REQUEST"
   "<INVERSEKINEMATICS-RESPONSE>"
   "INVERSEKINEMATICS-RESPONSE"
   "STARTSYSTEM"
   "<STARTSYSTEM-REQUEST>"
   "STARTSYSTEM-REQUEST"
   "<STARTSYSTEM-RESPONSE>"
   "STARTSYSTEM-RESPONSE"
   "TRAJECTORYPLANNER"
   "<TRAJECTORYPLANNER-REQUEST>"
   "TRAJECTORYPLANNER-REQUEST"
   "<TRAJECTORYPLANNER-RESPONSE>"
   "TRAJECTORYPLANNER-RESPONSE"
  ))

