# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborex/JointState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class JointState(genpy.Message):
  _md5sum = "b23171072f01fcca9054b0dc16f96450"
  _type = "roborex/JointState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point translation
float32 angle
float32 upper_bound
float32 lower_bound
int32 axis

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['translation','angle','upper_bound','lower_bound','axis']
  _slot_types = ['geometry_msgs/Point','float32','float32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       translation,angle,upper_bound,lower_bound,axis

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.translation is None:
        self.translation = geometry_msgs.msg.Point()
      if self.angle is None:
        self.angle = 0.
      if self.upper_bound is None:
        self.upper_bound = 0.
      if self.lower_bound is None:
        self.lower_bound = 0.
      if self.axis is None:
        self.axis = 0
    else:
      self.translation = geometry_msgs.msg.Point()
      self.angle = 0.
      self.upper_bound = 0.
      self.lower_bound = 0.
      self.axis = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d3fi().pack(_x.translation.x, _x.translation.y, _x.translation.z, _x.angle, _x.upper_bound, _x.lower_bound, _x.axis))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.translation is None:
        self.translation = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.translation.x, _x.translation.y, _x.translation.z, _x.angle, _x.upper_bound, _x.lower_bound, _x.axis,) = _get_struct_3d3fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d3fi().pack(_x.translation.x, _x.translation.y, _x.translation.z, _x.angle, _x.upper_bound, _x.lower_bound, _x.axis))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.translation is None:
        self.translation = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.translation.x, _x.translation.y, _x.translation.z, _x.angle, _x.upper_bound, _x.lower_bound, _x.axis,) = _get_struct_3d3fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d3fi = None
def _get_struct_3d3fi():
    global _struct_3d3fi
    if _struct_3d3fi is None:
        _struct_3d3fi = struct.Struct("<3d3fi")
    return _struct_3d3fi
