//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Roborex
{
    public class Command : Message
    {
        public const string RosMessageName = "roborex/Command";

        public float linear;
        public float angular;

        public Command()
        {
            this.linear = 0.0f;
            this.angular = 0.0f;
        }

        public Command(float linear, float angular)
        {
            this.linear = linear;
            this.angular = angular;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.linear));
            listOfSerializations.Add(BitConverter.GetBytes(this.angular));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.linear = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.angular = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "Command: " +
            "\nlinear: " + linear.ToString() +
            "\nangular: " + angular.ToString();
        }
    }
}
