// Generated by gencpp from file roborex/ForwardKinematics.msg
// DO NOT EDIT!


#ifndef ROBOREX_MESSAGE_FORWARDKINEMATICS_H
#define ROBOREX_MESSAGE_FORWARDKINEMATICS_H

#include <ros/service_traits.h>


#include <roborex/ForwardKinematicsRequest.h>
#include <roborex/ForwardKinematicsResponse.h>


namespace roborex
{

struct ForwardKinematics
{

typedef ForwardKinematicsRequest Request;
typedef ForwardKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForwardKinematics
} // namespace roborex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roborex::ForwardKinematics > {
  static const char* value()
  {
    return "f0117f65ce6a9862c9734b997e4a7382";
  }

  static const char* value(const ::roborex::ForwardKinematics&) { return value(); }
};

template<>
struct DataType< ::roborex::ForwardKinematics > {
  static const char* value()
  {
    return "roborex/ForwardKinematics";
  }

  static const char* value(const ::roborex::ForwardKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::roborex::ForwardKinematicsRequest> should match
// service_traits::MD5Sum< ::roborex::ForwardKinematics >
template<>
struct MD5Sum< ::roborex::ForwardKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roborex::ForwardKinematics >::value();
  }
  static const char* value(const ::roborex::ForwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborex::ForwardKinematicsRequest> should match
// service_traits::DataType< ::roborex::ForwardKinematics >
template<>
struct DataType< ::roborex::ForwardKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::roborex::ForwardKinematics >::value();
  }
  static const char* value(const ::roborex::ForwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roborex::ForwardKinematicsResponse> should match
// service_traits::MD5Sum< ::roborex::ForwardKinematics >
template<>
struct MD5Sum< ::roborex::ForwardKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roborex::ForwardKinematics >::value();
  }
  static const char* value(const ::roborex::ForwardKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborex::ForwardKinematicsResponse> should match
// service_traits::DataType< ::roborex::ForwardKinematics >
template<>
struct DataType< ::roborex::ForwardKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::roborex::ForwardKinematics >::value();
  }
  static const char* value(const ::roborex::ForwardKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOREX_MESSAGE_FORWARDKINEMATICS_H
