// Generated by gencpp from file roborex/ForwardKinematicsResponse.msg
// DO NOT EDIT!


#ifndef ROBOREX_MESSAGE_FORWARDKINEMATICSRESPONSE_H
#define ROBOREX_MESSAGE_FORWARDKINEMATICSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace roborex
{
template <class ContainerAllocator>
struct ForwardKinematicsResponse_
{
  typedef ForwardKinematicsResponse_<ContainerAllocator> Type;

  ForwardKinematicsResponse_()
    : target()  {
    }
  ForwardKinematicsResponse_(const ContainerAllocator& _alloc)
    : target(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ForwardKinematicsResponse_

typedef ::roborex::ForwardKinematicsResponse_<std::allocator<void> > ForwardKinematicsResponse;

typedef boost::shared_ptr< ::roborex::ForwardKinematicsResponse > ForwardKinematicsResponsePtr;
typedef boost::shared_ptr< ::roborex::ForwardKinematicsResponse const> ForwardKinematicsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborex::ForwardKinematicsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborex::ForwardKinematicsResponse_<ContainerAllocator1> & lhs, const ::roborex::ForwardKinematicsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborex::ForwardKinematicsResponse_<ContainerAllocator1> & lhs, const ::roborex::ForwardKinematicsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborex

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4b4e41b93b97f9307dacbb0795153e4";
  }

  static const char* value(const ::roborex::ForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4b4e41b93b97f93ULL;
  static const uint64_t static_value2 = 0x07dacbb0795153e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborex/ForwardKinematicsResponse";
  }

  static const char* value(const ::roborex::ForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose target\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::roborex::ForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForwardKinematicsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborex::ForwardKinematicsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborex::ForwardKinematicsResponse_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOREX_MESSAGE_FORWARDKINEMATICSRESPONSE_H
