// Generated by gencpp from file roborex/InverseKinematics.msg
// DO NOT EDIT!


#ifndef ROBOREX_MESSAGE_INVERSEKINEMATICS_H
#define ROBOREX_MESSAGE_INVERSEKINEMATICS_H

#include <ros/service_traits.h>


#include <roborex/InverseKinematicsRequest.h>
#include <roborex/InverseKinematicsResponse.h>


namespace roborex
{

struct InverseKinematics
{

typedef InverseKinematicsRequest Request;
typedef InverseKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InverseKinematics
} // namespace roborex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roborex::InverseKinematics > {
  static const char* value()
  {
    return "c44e167c0184aca769254292f802c4b0";
  }

  static const char* value(const ::roborex::InverseKinematics&) { return value(); }
};

template<>
struct DataType< ::roborex::InverseKinematics > {
  static const char* value()
  {
    return "roborex/InverseKinematics";
  }

  static const char* value(const ::roborex::InverseKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::roborex::InverseKinematicsRequest> should match
// service_traits::MD5Sum< ::roborex::InverseKinematics >
template<>
struct MD5Sum< ::roborex::InverseKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roborex::InverseKinematics >::value();
  }
  static const char* value(const ::roborex::InverseKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborex::InverseKinematicsRequest> should match
// service_traits::DataType< ::roborex::InverseKinematics >
template<>
struct DataType< ::roborex::InverseKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::roborex::InverseKinematics >::value();
  }
  static const char* value(const ::roborex::InverseKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roborex::InverseKinematicsResponse> should match
// service_traits::MD5Sum< ::roborex::InverseKinematics >
template<>
struct MD5Sum< ::roborex::InverseKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roborex::InverseKinematics >::value();
  }
  static const char* value(const ::roborex::InverseKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborex::InverseKinematicsResponse> should match
// service_traits::DataType< ::roborex::InverseKinematics >
template<>
struct DataType< ::roborex::InverseKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::roborex::InverseKinematics >::value();
  }
  static const char* value(const ::roborex::InverseKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOREX_MESSAGE_INVERSEKINEMATICS_H
