// Generated by gencpp from file roborex/Start.msg
// DO NOT EDIT!


#ifndef ROBOREX_MESSAGE_START_H
#define ROBOREX_MESSAGE_START_H

#include <ros/service_traits.h>


#include <roborex/StartRequest.h>
#include <roborex/StartResponse.h>


namespace roborex
{

struct Start
{

typedef StartRequest Request;
typedef StartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Start
} // namespace roborex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roborex::Start > {
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::roborex::Start&) { return value(); }
};

template<>
struct DataType< ::roborex::Start > {
  static const char* value()
  {
    return "roborex/Start";
  }

  static const char* value(const ::roborex::Start&) { return value(); }
};


// service_traits::MD5Sum< ::roborex::StartRequest> should match
// service_traits::MD5Sum< ::roborex::Start >
template<>
struct MD5Sum< ::roborex::StartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roborex::Start >::value();
  }
  static const char* value(const ::roborex::StartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborex::StartRequest> should match
// service_traits::DataType< ::roborex::Start >
template<>
struct DataType< ::roborex::StartRequest>
{
  static const char* value()
  {
    return DataType< ::roborex::Start >::value();
  }
  static const char* value(const ::roborex::StartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roborex::StartResponse> should match
// service_traits::MD5Sum< ::roborex::Start >
template<>
struct MD5Sum< ::roborex::StartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roborex::Start >::value();
  }
  static const char* value(const ::roborex::StartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborex::StartResponse> should match
// service_traits::DataType< ::roborex::Start >
template<>
struct DataType< ::roborex::StartResponse>
{
  static const char* value()
  {
    return DataType< ::roborex::Start >::value();
  }
  static const char* value(const ::roborex::StartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOREX_MESSAGE_START_H
