// Generated by gencpp from file roborex/StartSystemResponse.msg
// DO NOT EDIT!


#ifndef ROBOREX_MESSAGE_STARTSYSTEMRESPONSE_H
#define ROBOREX_MESSAGE_STARTSYSTEMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborex
{
template <class ContainerAllocator>
struct StartSystemResponse_
{
  typedef StartSystemResponse_<ContainerAllocator> Type;

  StartSystemResponse_()
    : succeeded(false)  {
    }
  StartSystemResponse_(const ContainerAllocator& _alloc)
    : succeeded(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeeded_type;
  _succeeded_type succeeded;





  typedef boost::shared_ptr< ::roborex::StartSystemResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborex::StartSystemResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartSystemResponse_

typedef ::roborex::StartSystemResponse_<std::allocator<void> > StartSystemResponse;

typedef boost::shared_ptr< ::roborex::StartSystemResponse > StartSystemResponsePtr;
typedef boost::shared_ptr< ::roborex::StartSystemResponse const> StartSystemResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborex::StartSystemResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborex::StartSystemResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborex::StartSystemResponse_<ContainerAllocator1> & lhs, const ::roborex::StartSystemResponse_<ContainerAllocator2> & rhs)
{
  return lhs.succeeded == rhs.succeeded;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborex::StartSystemResponse_<ContainerAllocator1> & lhs, const ::roborex::StartSystemResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborex

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roborex::StartSystemResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborex::StartSystemResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborex::StartSystemResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborex::StartSystemResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborex::StartSystemResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborex::StartSystemResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborex::StartSystemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95e696a0d10686913abb262e0b4cbbcf";
  }

  static const char* value(const ::roborex::StartSystemResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95e696a0d1068691ULL;
  static const uint64_t static_value2 = 0x3abb262e0b4cbbcfULL;
};

template<class ContainerAllocator>
struct DataType< ::roborex::StartSystemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborex/StartSystemResponse";
  }

  static const char* value(const ::roborex::StartSystemResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborex::StartSystemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool succeeded\n"
;
  }

  static const char* value(const ::roborex::StartSystemResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborex::StartSystemResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeeded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartSystemResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborex::StartSystemResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborex::StartSystemResponse_<ContainerAllocator>& v)
  {
    s << indent << "succeeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeeded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOREX_MESSAGE_STARTSYSTEMRESPONSE_H
