//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Roborex
{
    public class ForwardKinematicsResponse : Message
    {
        public const string RosMessageName = "roborex/ForwardKinematics";

        public Geometry.Pose target;

        public ForwardKinematicsResponse()
        {
            this.target = new Geometry.Pose();
        }

        public ForwardKinematicsResponse(Geometry.Pose target)
        {
            this.target = target;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(target.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.target.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "ForwardKinematicsResponse: " +
            "\ntarget: " + target.ToString();
        }
    }
}
