//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Roborex
{
    public class ForwardKinematicsRequest : Message
    {
        public const string RosMessageName = "roborex/ForwardKinematics";

        public JointState[] joints;

        public ForwardKinematicsRequest()
        {
            this.joints = new JointState[0];
        }

        public ForwardKinematicsRequest(JointState[] joints)
        {
            this.joints = joints;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(joints.Length));
            foreach(var entry in joints)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var jointsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.joints= new JointState[jointsArrayLength];
            for(var i = 0; i < jointsArrayLength; i++)
            {
                this.joints[i] = new JointState();
                offset = this.joints[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "ForwardKinematicsRequest: " +
            "\njoints: " + System.String.Join(", ", joints.ToList());
        }
    }
}
