//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Roborex
{
    public class InverseKinematicsResponse : Message
    {
        public const string RosMessageName = "roborex/InverseKinematics";

        public ArmPose arm_pose;

        public InverseKinematicsResponse()
        {
            this.arm_pose = new ArmPose();
        }

        public InverseKinematicsResponse(ArmPose arm_pose)
        {
            this.arm_pose = arm_pose;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(arm_pose.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.arm_pose.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "InverseKinematicsResponse: " +
            "\narm_pose: " + arm_pose.ToString();
        }
    }
}
