//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Roborex
{
    public class StartSystemResponse : Message
    {
        public const string RosMessageName = "roborex/StartSystem";

        public bool succeeded;

        public StartSystemResponse()
        {
            this.succeeded = false;
        }

        public StartSystemResponse(bool succeeded)
        {
            this.succeeded = succeeded;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.succeeded));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.succeeded = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "StartSystemResponse: " +
            "\nsucceeded: " + succeeded.ToString();
        }
    }
}
