// Generated by gencpp from file niryo_moveit/MoverServiceRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_MOVEIT_MESSAGE_MOVERSERVICEREQUEST_H
#define NIRYO_MOVEIT_MESSAGE_MOVERSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_moveit/NiryoMoveitJoints.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace niryo_moveit
{
template <class ContainerAllocator>
struct MoverServiceRequest_
{
  typedef MoverServiceRequest_<ContainerAllocator> Type;

  MoverServiceRequest_()
    : joints_input()
    , pick_pose()
    , place_pose()  {
    }
  MoverServiceRequest_(const ContainerAllocator& _alloc)
    : joints_input(_alloc)
    , pick_pose(_alloc)
    , place_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator>  _joints_input_type;
  _joints_input_type joints_input;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pick_pose_type;
  _pick_pose_type pick_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _place_pose_type;
  _place_pose_type place_pose;





  typedef boost::shared_ptr< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoverServiceRequest_

typedef ::niryo_moveit::MoverServiceRequest_<std::allocator<void> > MoverServiceRequest;

typedef boost::shared_ptr< ::niryo_moveit::MoverServiceRequest > MoverServiceRequestPtr;
typedef boost::shared_ptr< ::niryo_moveit::MoverServiceRequest const> MoverServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator1> & lhs, const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joints_input == rhs.joints_input &&
    lhs.pick_pose == rhs.pick_pose &&
    lhs.place_pose == rhs.place_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator1> & lhs, const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_moveit

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "375ea90ec3b506491b1fc61b79625a40";
  }

  static const char* value(const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x375ea90ec3b50649ULL;
  static const uint64_t static_value2 = 0x1b1fc61b79625a40ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_moveit/MoverServiceRequest";
  }

  static const char* value(const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NiryoMoveitJoints joints_input\n"
"geometry_msgs/Pose pick_pose\n"
"geometry_msgs/Pose place_pose\n"
"\n"
"================================================================================\n"
"MSG: niryo_moveit/NiryoMoveitJoints\n"
"float64 joint_00\n"
"float64 joint_01\n"
"float64 joint_02\n"
"float64 joint_03\n"
"float64 joint_04\n"
"float64 joint_05\n"
"geometry_msgs/Pose pick_pose\n"
"geometry_msgs/Pose place_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_input);
      stream.next(m.pick_pose);
      stream.next(m.place_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoverServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_moveit::MoverServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_moveit::MoverServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "joints_input: ";
    s << std::endl;
    Printer< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints_input);
    s << indent << "pick_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pick_pose);
    s << indent << "place_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.place_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_MOVEIT_MESSAGE_MOVERSERVICEREQUEST_H
