// Generated by gencpp from file niryo_moveit/NiryoMoveitJoints.msg
// DO NOT EDIT!


#ifndef NIRYO_MOVEIT_MESSAGE_NIRYOMOVEITJOINTS_H
#define NIRYO_MOVEIT_MESSAGE_NIRYOMOVEITJOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace niryo_moveit
{
template <class ContainerAllocator>
struct NiryoMoveitJoints_
{
  typedef NiryoMoveitJoints_<ContainerAllocator> Type;

  NiryoMoveitJoints_()
    : joint_00(0.0)
    , joint_01(0.0)
    , joint_02(0.0)
    , joint_03(0.0)
    , joint_04(0.0)
    , joint_05(0.0)
    , pick_pose()
    , place_pose()  {
    }
  NiryoMoveitJoints_(const ContainerAllocator& _alloc)
    : joint_00(0.0)
    , joint_01(0.0)
    , joint_02(0.0)
    , joint_03(0.0)
    , joint_04(0.0)
    , joint_05(0.0)
    , pick_pose(_alloc)
    , place_pose(_alloc)  {
  (void)_alloc;
    }



   typedef double _joint_00_type;
  _joint_00_type joint_00;

   typedef double _joint_01_type;
  _joint_01_type joint_01;

   typedef double _joint_02_type;
  _joint_02_type joint_02;

   typedef double _joint_03_type;
  _joint_03_type joint_03;

   typedef double _joint_04_type;
  _joint_04_type joint_04;

   typedef double _joint_05_type;
  _joint_05_type joint_05;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pick_pose_type;
  _pick_pose_type pick_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _place_pose_type;
  _place_pose_type place_pose;





  typedef boost::shared_ptr< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> const> ConstPtr;

}; // struct NiryoMoveitJoints_

typedef ::niryo_moveit::NiryoMoveitJoints_<std::allocator<void> > NiryoMoveitJoints;

typedef boost::shared_ptr< ::niryo_moveit::NiryoMoveitJoints > NiryoMoveitJointsPtr;
typedef boost::shared_ptr< ::niryo_moveit::NiryoMoveitJoints const> NiryoMoveitJointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator1> & lhs, const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator2> & rhs)
{
  return lhs.joint_00 == rhs.joint_00 &&
    lhs.joint_01 == rhs.joint_01 &&
    lhs.joint_02 == rhs.joint_02 &&
    lhs.joint_03 == rhs.joint_03 &&
    lhs.joint_04 == rhs.joint_04 &&
    lhs.joint_05 == rhs.joint_05 &&
    lhs.pick_pose == rhs.pick_pose &&
    lhs.place_pose == rhs.place_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator1> & lhs, const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_moveit

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb9a754ca01417c49ae5e00219146bda";
  }

  static const char* value(const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb9a754ca01417c4ULL;
  static const uint64_t static_value2 = 0x9ae5e00219146bdaULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_moveit/NiryoMoveitJoints";
  }

  static const char* value(const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 joint_00\n"
"float64 joint_01\n"
"float64 joint_02\n"
"float64 joint_03\n"
"float64 joint_04\n"
"float64 joint_05\n"
"geometry_msgs/Pose pick_pose\n"
"geometry_msgs/Pose place_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_00);
      stream.next(m.joint_01);
      stream.next(m.joint_02);
      stream.next(m.joint_03);
      stream.next(m.joint_04);
      stream.next(m.joint_05);
      stream.next(m.pick_pose);
      stream.next(m.place_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NiryoMoveitJoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_moveit::NiryoMoveitJoints_<ContainerAllocator>& v)
  {
    s << indent << "joint_00: ";
    Printer<double>::stream(s, indent + "  ", v.joint_00);
    s << indent << "joint_01: ";
    Printer<double>::stream(s, indent + "  ", v.joint_01);
    s << indent << "joint_02: ";
    Printer<double>::stream(s, indent + "  ", v.joint_02);
    s << indent << "joint_03: ";
    Printer<double>::stream(s, indent + "  ", v.joint_03);
    s << indent << "joint_04: ";
    Printer<double>::stream(s, indent + "  ", v.joint_04);
    s << indent << "joint_05: ";
    Printer<double>::stream(s, indent + "  ", v.joint_05);
    s << indent << "pick_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pick_pose);
    s << indent << "place_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.place_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_MOVEIT_MESSAGE_NIRYOMOVEITJOINTS_H
